loss: !!python/object:gluonts.torch.modules.loss.NegativeLogLikelihood
  __dict__:
    beta: 0.0
  __fields_set__: !!set {}
  __private_attribute_values__: {}
lr: 0.001
model_kwargs:
  cardinality:
  - 1
  context_length: 9
  default_scale: null
  distr_output: !!python/object:gluonts.torch.distributions.negative_binomial.NegativeBinomialOutput
    __init_args__: !!python/object/apply:collections.OrderedDict
    - []
  dropout_rate: 0.2
  embedding_dimension: null
  freq: W
  hidden_size: 40
  lags_seq: null
  num_feat_dynamic_real: 4
  num_feat_static_cat: 1
  num_feat_static_real: 1
  num_layers: 4
  num_parallel_samples: 100
  prediction_length: 9
  scaling: true
patience: 10
weight_decay: 1.0e-08
